### ISSUE TITLE
Getting PatchOp Operations

### ISSUE THREAD

**Issue by always-akshat** [scimmyjs/scimmy-routers#14]
First off, sorry for adding all these issues. I am trying to implement a enterprise SCIM gateway on top of this. 

Another problem I am seeing is the express handlers (views) not passing the operations for the PatchOp

Here's an example PATCH request  
<img width="1090" alt="Screenshot 2024-02-21 at 2 06 32 PM" src="https://github.com/scimmyjs/scimmy-routers/assets/3632790/06d54286-6d95-430d-a844-85fe2fdcb76a">

Here's my code that handles the request and passes it to a controller. 

`app.ts`
```
import * as UserController from "./users/users.controller";
...
SCIMMY.Resources.declare(SCIMMY.Resources.User)
  .ingress(UserController.ingress)
  .egress(UserController.egress)
  .degress((resource: any) => {
    console.log(`Request to delete user ${resource}`);
  });  
...
 ```
 
 `users.controller.ts`
 
 ```
 import { User as UserResource } from "lib/resources/user";
 ...
 export async function egress(resource: UserResource) {
  console.log(`resource`, {
  ...resource
  });

  const orgId = 1;
  const mappedFilters = mapScimToUserFilter(resource.filter ?? []);
  console.dir(
    {
      mappedFilters,
    },
    { depth: null }
  );
  const { handle } = findUserQuery;
  return handle({
    orgId,
    filter: mappedFilters,
  });
}
 ```
 
 
 When sending the mentioned PATCH request, my controller doesn't get any details about the PATCH Op
 
 `log from the controller`
 ```
 resource {
  id: '295',
  filter: Filter(1) [ { id: [Array] }, expression: 'id eq "295"' ]
}
 ```
 
Do I need to add another patch handler?

**Comment by always-akshat** [comment]
Closing this since I figured out how this works. 

For anyone else who stumbles upon this problem -- The way _PATCH_ works is by using the _ingress_ and _egress_ together. The request is first sent to the egress controller to parse the filter and get the Resource. Then, it creates an instance of updated Resource and passes that to the _ingress_ handler.

**Comment by always-akshat** [comment]
Closing this since I figured out how this works.

For anyone else who stumbles upon this problem -- The way PATCH works is by using the ingress and egress together. The request is first sent to the egress controller to parse the filter and get the Resource. Then, it creates an instance of updated Resource and passes that to the ingress handler.

**Comment by sleelin** [comment]
Hi @always-akshat,
Thanks for following up with the answer to your own question!

To clarify further, the `SCIMMY.Resources.User` instance remains the same for both the ingress and egress methods while handling the request. When the `patch` method is called, the return value of the egress method is used to create an instance of the `SCIMMY.Schemas.User` _schema_. This is then passed to the `apply` method of the `SCIMMY.Messages.PatchOp` class. The operations in the PatchOp are then applied atomically to the schema instance, which enforces mutability and validity requirements. If the PatchOp is completed (i.e. all operations are valid and successful), the `apply` method then calls the ingress handler with the patched schema instance, which is intended to write back any changes to your data source. The return value of the ingress handler is then used to create a _new_ instance of the `SCIMMY.Schemas.User` schema class, which is then compared to the schema instance created initially with the value returned by the egress handler. If any property at any depth differs, one final instance of the `SCIMMY.Schemas.User` schema class is created by the `patch` method, with the directionality set to "out", and the basepath and attribute filters supplied. The process is identical for the `patch` method of the `SCIMMY.Resources.Group` class, but using the `SCIMMY.Schemas.Group` schema class instead.

Also, I believe this issue may be better suited being located in the [main SCIMMY repository](https://github.com/scimmyjs/scimmy), as the relevant handling code lives there, so have transferred it over there.

Thanks,
Sam
